// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/sebasvil20/TalksUpAPI/src/api/app/providers"
	"github.com/sebasvil20/TalksUpAPI/src/api/controllers"
	"github.com/sebasvil20/TalksUpAPI/src/api/repository"
	"github.com/sebasvil20/TalksUpAPI/src/api/services"
)

// Injectors from app.go:

func StartProviders() *ProviderRoute {
	userRepository := providers.ProvideUserRepository()
	userService := providers.ProvideUserService(userRepository)
	userController := providers.ProvideUserController(userService)
	providerRoute := &ProviderRoute{
		UserController: userController,
	}
	return providerRoute
}

// app.go:

type ProviderRoute struct {
	UserController *controllers.UserController
}

var userSet = wire.NewSet(providers.ProvideUserRepository, wire.Bind(new(repository.IUserRepository), new(*repository.UserRepository)), providers.ProvideUserService, wire.Bind(new(services.IUserService), new(*services.UserService)), providers.ProvideUserController, wire.Bind(new(controllers.IUserController), new(*controllers.UserController)))

var setProvider = wire.NewSet(
	userSet, wire.Struct(new(ProviderRoute), "UserController"),
)
